# Generated by Django 4.1.1 on 2022-09-12 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_bookstoreslist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=30)),
                ('publish_year', models.DateField()),
                ('publisher', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=30)),
                ('isbn', models.IntegerField(max_length=13)),
                ('price', models.FloatField()),
                ('book_thumbnail', models.ImageField(blank=True, null=True, upload_to=None)),
                ('bookstore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bookstoreslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
