# Generated by Django 4.1.1 on 2022-09-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='books',
            new_name='user_book',
        ),
    ]
