# Generated by Django 4.1 on 2022-09-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_books_cartitem_user_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
